### ISSUE TITLE
GKE Inference instructions improvements

### ISSUE THREAD

**Issue by abdallag** [GoogleCloudPlatform/llm-pipeline-examples#41]
- Add --project parameter to gcloud run commands
- Add GCS bucket creation steps, see https://github.com/GoogleCloudPlatform/llm-pipeline-examples/tree/main#instructions for reference
- Move PROJECT_ID and CONVERTED_MODEL_UPLOAD_PATH to a parameter instead of having to update them in environment file

- Add a "Quick Start Guide" section right after the Intro section. The section should be very compact and contain consecutive instructions to get up and running quickly, see https://github.com/GoogleCloudPlatform/llm-pipeline-examples/tree/main#quick-start-guide for reference
- Add a note to give the default service account the Editor permissions in case it didn't get it

**Comment by Chris113113** [comment]
Fixed in #55
