### ISSUE TITLE
GKE inference fails with bucket creation error

### ISSUE THREAD

**Issue by abdallag** [GoogleCloudPlatform/llm-pipeline-examples#42]
https://screenshot.googleplex.com/3qxKK7T8sM8VB9d

The container shouldn't be creating new GCS buckets. It should use what ever GCS bucket that is provided by the user.

**Comment by Chris113113** [comment]
Will resolve this by using the converted_model_path to set the GCS path for terraform files.

**Comment by Chris113113** [comment]
Fixed in #55
