### ISSUE TITLE
Trainer parameters seem wrong.

### ISSUE THREAD

**Issue by Keloo** [GoogleCloudPlatform/llm-pipeline-examples#60]
There seem to be more parameters passed to run_batch.sh than expected.

<img width="1642" alt="Screenshot 2023-07-26 at 19 21 21" src="https://github.com/GoogleCloudPlatform/llm-pipeline-examples/assets/5405232/cc6d5282-ecc2-476a-be02-bb6011cb6a38">

\
\
This as consequence makes the trainer_config.json incorrect. 

<img width="1244" alt="Screenshot 2023-07-26 at 19 16 45" src="https://github.com/GoogleCloudPlatform/llm-pipeline-examples/assets/5405232/a5f5dff2-7321-40e0-a53c-4d695b11ce6c">

**Comment by Chris113113** [comment]
After talking offline we discovered the readme was referring to the old repo location ( llm-pipeline.git ) rather than the current location (llm-pipeline-examples.git )

This caused an issue in the pipeline params being provided to the training image.

Resolved in #61
